# Constants

from typing import Final

CID_LENGTH: Final[int] = 59
COMMITTEE_ID_LENGTH: Final[int] = 32
TITLE_MAX_BYTES: Final[int] = 123
MICROALGOS_TO_ALGOS: Final[int] = 1_000_000

MIN_REQUESTED_ALGO_AMOUNT: Final[int] = 10_000
MAX_REQUESTED_ALGO_AMOUNT_SMALL: Final[int] = 50_000
MAX_REQUESTED_ALGO_AMOUNT_MEDIUM: Final[int] = 250_000
MAX_REQUESTED_ALGO_AMOUNT_LARGE: Final[int] = 500_000
