name: Docs CI action
description: 'Lint docs, build mdBook'

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install pre-commit
      shell: bash
      run: pip install --upgrade pip pre-commit

    - name: Cache pre-commit hooks
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: precommit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: precommit-${{ runner.os }}-

    - name: Run pre-commit hooks
      shell: bash
      run: |
        pre-commit run markdownlint --all-files --verbose
        pre-commit run trailing-whitespace --all-files --verbose
        pre-commit run lychee-docker --all-files --verbose

    - name: Build mdBook
      shell: bash
      run: docker compose run mdbook build
