name: Docs CI action
description: 'Lint docs, build mdBook'

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install pre-commit
      shell: bash
      run: pip install --upgrade pip pre-commit

    - name: Cache pre-commit hooks
      uses: actions/cache@v5
      with:
        path: ~/.cache/pre-commit
        key: precommit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: precommit-${{ runner.os }}-

    - name: Run pre-commit hooks
      shell: bash
      run: |
        pre-commit run markdownlint --all-files --verbose
        pre-commit run trailing-whitespace --all-files --verbose

    - name: Run soft pre-commit hooks as a warning
      shell: bash
      run: |
        pre-commit run lychee --all-files --verbose || true

    - name: Prepare mdBook output directory
      shell: bash
      run: |
        mkdir -p book
        chmod -R 777 book

    - name: Build mdBook
      shell: bash
      run: docker compose run mdbook build
