name: Docs CI action
description: 'Lint docs, build and test mdBook'
runs:
  using: "composite"

  steps:
    - name: Check Markdown linting
      uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: |
          README.md
          SECURITY.md
          docs/**/*.md

    - name: Link Checker
      uses: lycheeverse/lychee-action@v2
      with:
        fail: true

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v2
      with:
        mdbook-version: '0.4.52'

    - name: Test mdBook
      shell: bash
      run: mdbook test

    - name: Install mdBook Mermaid plugin
      shell: bash
      run: cargo install mdbook-mermaid && mdbook-mermaid install .

    - name: Build mdBook
      shell: bash
      run: mdbook build
